// Generated FFI bindings from Noir's selected OpenTUI v0.5.1 declarations.
// Regenerate with: dart run ffigen --config ffigen_dynamic.yaml
// Do not edit manually.
// ignore_for_file: unused_element, unused_field

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Auto-generated bindings for OpenTUI
class OpenTuiBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  OpenTuiBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  OpenTuiBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int createRenderer(
    int width,
    int height,
    int bufferedDestinationKind,
    int remoteModeValue,
    ffi.Pointer<ffi.Void> feedPtr,
  ) {
    return _createRenderer(
      width,
      height,
      bufferedDestinationKind,
      remoteModeValue,
      feedPtr,
    );
  }

  late final _createRendererPtr =
      _lookup<
        ffi.NativeFunction<
          OpenTuiHandle Function(
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint8,
            ffi.Uint8,
            ffi.Pointer<ffi.Void>,
          )
        >
      >('createRenderer');
  late final _createRenderer = _createRendererPtr
      .asFunction<int Function(int, int, int, int, ffi.Pointer<ffi.Void>)>();

  void destroyRenderer(int renderer) {
    return _destroyRenderer(renderer);
  }

  late final _destroyRendererPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle)>>(
        'destroyRenderer',
      );
  late final _destroyRenderer = _destroyRendererPtr
      .asFunction<void Function(int)>();

  int render(int renderer, bool force) {
    return _render(renderer, force);
  }

  late final _renderPtr =
      _lookup<ffi.NativeFunction<ffi.Uint8 Function(OpenTuiHandle, ffi.Bool)>>(
        'render',
      );
  late final _render = _renderPtr.asFunction<int Function(int, bool)>();

  int getNextBuffer(int renderer) {
    return _getNextBuffer(renderer);
  }

  late final _getNextBufferPtr =
      _lookup<ffi.NativeFunction<OpenTuiHandle Function(OpenTuiHandle)>>(
        'getNextBuffer',
      );
  late final _getNextBuffer = _getNextBufferPtr.asFunction<int Function(int)>();

  int getCurrentBuffer(int renderer) {
    return _getCurrentBuffer(renderer);
  }

  late final _getCurrentBufferPtr =
      _lookup<ffi.NativeFunction<OpenTuiHandle Function(OpenTuiHandle)>>(
        'getCurrentBuffer',
      );
  late final _getCurrentBuffer = _getCurrentBufferPtr
      .asFunction<int Function(int)>();

  void resizeRenderer(int renderer, int width, int height) {
    return _resizeRenderer(renderer, width, height);
  }

  late final _resizeRendererPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(OpenTuiHandle, ffi.Uint32, ffi.Uint32)
        >
      >('resizeRenderer');
  late final _resizeRenderer = _resizeRendererPtr
      .asFunction<void Function(int, int, int)>();

  void setBackgroundColor(int renderer, ffi.Pointer<ffi.Uint16> color) {
    return _setBackgroundColor(renderer, color);
  }

  late final _setBackgroundColorPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(OpenTuiHandle, ffi.Pointer<ffi.Uint16>)
        >
      >('setBackgroundColor');
  late final _setBackgroundColor = _setBackgroundColorPtr
      .asFunction<void Function(int, ffi.Pointer<ffi.Uint16>)>();

  void clearTerminal(int renderer) {
    return _clearTerminal(renderer);
  }

  late final _clearTerminalPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle)>>(
        'clearTerminal',
      );
  late final _clearTerminal = _clearTerminalPtr
      .asFunction<void Function(int)>();

  bool copyToClipboardOSC52(
    int renderer,
    int target,
    ffi.Pointer<ffi.Uint8> text,
    int textLen,
  ) {
    return _copyToClipboardOSC52(renderer, target, text, textLen);
  }

  late final _copyToClipboardOSC52Ptr =
      _lookup<
        ffi.NativeFunction<
          ffi.Bool Function(
            OpenTuiHandle,
            ffi.Uint8,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
          )
        >
      >('copyToClipboardOSC52');
  late final _copyToClipboardOSC52 = _copyToClipboardOSC52Ptr
      .asFunction<bool Function(int, int, ffi.Pointer<ffi.Uint8>, int)>();

  bool clearClipboardOSC52(int renderer, int target) {
    return _clearClipboardOSC52(renderer, target);
  }

  late final _clearClipboardOSC52Ptr =
      _lookup<ffi.NativeFunction<ffi.Bool Function(OpenTuiHandle, ffi.Uint8)>>(
        'clearClipboardOSC52',
      );
  late final _clearClipboardOSC52 = _clearClipboardOSC52Ptr
      .asFunction<bool Function(int, int)>();

  int getBufferWidth(int buffer) {
    return _getBufferWidth(buffer);
  }

  late final _getBufferWidthPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(OpenTuiHandle)>>(
        'getBufferWidth',
      );
  late final _getBufferWidth = _getBufferWidthPtr
      .asFunction<int Function(int)>();

  int getBufferHeight(int buffer) {
    return _getBufferHeight(buffer);
  }

  late final _getBufferHeightPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(OpenTuiHandle)>>(
        'getBufferHeight',
      );
  late final _getBufferHeight = _getBufferHeightPtr
      .asFunction<int Function(int)>();

  void bufferClear(int buffer, ffi.Pointer<ffi.Uint16> bg) {
    return _bufferClear(buffer, bg);
  }

  late final _bufferClearPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(OpenTuiHandle, ffi.Pointer<ffi.Uint16>)
        >
      >('bufferClear');
  late final _bufferClear = _bufferClearPtr
      .asFunction<void Function(int, ffi.Pointer<ffi.Uint16>)>();

  void bufferDrawText(
    int buffer,
    ffi.Pointer<ffi.Uint8> text,
    int textLen,
    int x,
    int y,
    ffi.Pointer<ffi.Uint16> fg,
    ffi.Pointer<ffi.Uint16> bg,
    int attributes,
  ) {
    return _bufferDrawText(buffer, text, textLen, x, y, fg, bg, attributes);
  }

  late final _bufferDrawTextPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            OpenTuiHandle,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint16>,
            ffi.Pointer<ffi.Uint16>,
            ffi.Uint32,
          )
        >
      >('bufferDrawText');
  late final _bufferDrawText = _bufferDrawTextPtr
      .asFunction<
        void Function(
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          int,
          ffi.Pointer<ffi.Uint16>,
          ffi.Pointer<ffi.Uint16>,
          int,
        )
      >();

  void bufferFillRect(
    int buffer,
    int x,
    int y,
    int width,
    int height,
    ffi.Pointer<ffi.Uint16> bg,
  ) {
    return _bufferFillRect(buffer, x, y, width, height, bg);
  }

  late final _bufferFillRectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            OpenTuiHandle,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint16>,
          )
        >
      >('bufferFillRect');
  late final _bufferFillRect = _bufferFillRectPtr
      .asFunction<
        void Function(int, int, int, int, int, ffi.Pointer<ffi.Uint16>)
      >();

  void bufferDrawBox(
    int buffer,
    int x,
    int y,
    int width,
    int height,
    ffi.Pointer<ffi.Uint32> borderChars,
    int packedOptions,
    ffi.Pointer<ffi.Uint16> borderColor,
    ffi.Pointer<ffi.Uint16> backgroundColor,
    ffi.Pointer<ffi.Uint16> titleColor,
    ffi.Pointer<ffi.Uint8> title,
    int titleLen,
    ffi.Pointer<ffi.Uint8> bottomTitle,
    int bottomTitleLen,
  ) {
    return _bufferDrawBox(
      buffer,
      x,
      y,
      width,
      height,
      borderChars,
      packedOptions,
      borderColor,
      backgroundColor,
      titleColor,
      title,
      titleLen,
      bottomTitle,
      bottomTitleLen,
    );
  }

  late final _bufferDrawBoxPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            OpenTuiHandle,
            ffi.Int32,
            ffi.Int32,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint32>,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint16>,
            ffi.Pointer<ffi.Uint16>,
            ffi.Pointer<ffi.Uint16>,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
          )
        >
      >('bufferDrawBox');
  late final _bufferDrawBox = _bufferDrawBoxPtr
      .asFunction<
        void Function(
          int,
          int,
          int,
          int,
          int,
          ffi.Pointer<ffi.Uint32>,
          int,
          ffi.Pointer<ffi.Uint16>,
          ffi.Pointer<ffi.Uint16>,
          ffi.Pointer<ffi.Uint16>,
          ffi.Pointer<ffi.Uint8>,
          int,
          ffi.Pointer<ffi.Uint8>,
          int,
        )
      >();

  ffi.Pointer<ffi.Uint32> bufferGetCharPtr(int buffer) {
    return _bufferGetCharPtr(buffer);
  }

  late final _bufferGetCharPtrPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Uint32> Function(OpenTuiHandle)>
      >('bufferGetCharPtr');
  late final _bufferGetCharPtr = _bufferGetCharPtrPtr
      .asFunction<ffi.Pointer<ffi.Uint32> Function(int)>();

  ffi.Pointer<ffi.Uint16> bufferGetFgPtr(int buffer) {
    return _bufferGetFgPtr(buffer);
  }

  late final _bufferGetFgPtrPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Uint16> Function(OpenTuiHandle)>
      >('bufferGetFgPtr');
  late final _bufferGetFgPtr = _bufferGetFgPtrPtr
      .asFunction<ffi.Pointer<ffi.Uint16> Function(int)>();

  ffi.Pointer<ffi.Uint16> bufferGetBgPtr(int buffer) {
    return _bufferGetBgPtr(buffer);
  }

  late final _bufferGetBgPtrPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Uint16> Function(OpenTuiHandle)>
      >('bufferGetBgPtr');
  late final _bufferGetBgPtr = _bufferGetBgPtrPtr
      .asFunction<ffi.Pointer<ffi.Uint16> Function(int)>();

  ffi.Pointer<ffi.Uint32> bufferGetAttributesPtr(int buffer) {
    return _bufferGetAttributesPtr(buffer);
  }

  late final _bufferGetAttributesPtrPtr =
      _lookup<
        ffi.NativeFunction<ffi.Pointer<ffi.Uint32> Function(OpenTuiHandle)>
      >('bufferGetAttributesPtr');
  late final _bufferGetAttributesPtr = _bufferGetAttributesPtrPtr
      .asFunction<ffi.Pointer<ffi.Uint32> Function(int)>();

  int bufferGetRealCharSize(int buffer) {
    return _bufferGetRealCharSize(buffer);
  }

  late final _bufferGetRealCharSizePtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(OpenTuiHandle)>>(
        'bufferGetRealCharSize',
      );
  late final _bufferGetRealCharSize = _bufferGetRealCharSizePtr
      .asFunction<int Function(int)>();

  int bufferWriteResolvedChars(
    int buffer,
    ffi.Pointer<ffi.Uint8> output,
    int outputLen,
    bool addLineBreaks,
  ) {
    return _bufferWriteResolvedChars(buffer, output, outputLen, addLineBreaks);
  }

  late final _bufferWriteResolvedCharsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(
            OpenTuiHandle,
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
            ffi.Bool,
          )
        >
      >('bufferWriteResolvedChars');
  late final _bufferWriteResolvedChars = _bufferWriteResolvedCharsPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Uint8>, int, bool)>();

  void bufferSetCellWithAlphaBlending(
    int buffer,
    int x,
    int y,
    int character,
    ffi.Pointer<ffi.Uint16> fg,
    ffi.Pointer<ffi.Uint16> bg,
    int attributes,
  ) {
    return _bufferSetCellWithAlphaBlending(
      buffer,
      x,
      y,
      character,
      fg,
      bg,
      attributes,
    );
  }

  late final _bufferSetCellWithAlphaBlendingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            OpenTuiHandle,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Pointer<ffi.Uint16>,
            ffi.Pointer<ffi.Uint16>,
            ffi.Uint32,
          )
        >
      >('bufferSetCellWithAlphaBlending');
  late final _bufferSetCellWithAlphaBlending =
      _bufferSetCellWithAlphaBlendingPtr
          .asFunction<
            void Function(
              int,
              int,
              int,
              int,
              ffi.Pointer<ffi.Uint16>,
              ffi.Pointer<ffi.Uint16>,
              int,
            )
          >();

  void drawFrameBuffer(
    int target,
    int destX,
    int destY,
    int frameBuffer,
    int sourceX,
    int sourceY,
    int sourceWidth,
    int sourceHeight,
  ) {
    return _drawFrameBuffer(
      target,
      destX,
      destY,
      frameBuffer,
      sourceX,
      sourceY,
      sourceWidth,
      sourceHeight,
    );
  }

  late final _drawFrameBufferPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            OpenTuiHandle,
            ffi.Int32,
            ffi.Int32,
            OpenTuiHandle,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
          )
        >
      >('drawFrameBuffer');
  late final _drawFrameBuffer = _drawFrameBufferPtr
      .asFunction<void Function(int, int, int, int, int, int, int, int)>();

  void bufferResize(int buffer, int width, int height) {
    return _bufferResize(buffer, width, height);
  }

  late final _bufferResizePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(OpenTuiHandle, ffi.Uint32, ffi.Uint32)
        >
      >('bufferResize');
  late final _bufferResize = _bufferResizePtr
      .asFunction<void Function(int, int, int)>();

  /// Native clip and opacity stacks. Every native write funnel honours both
  /// (buffer.zig validateAndIndex -> isPointInScissor, and getCurrentOpacity).
  /// Exposed on the raw binding surface; Noir's own clip seam stays in Dart.
  void bufferPushScissorRect(int buffer, int x, int y, int width, int height) {
    return _bufferPushScissorRect(buffer, x, y, width, height);
  }

  late final _bufferPushScissorRectPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            OpenTuiHandle,
            ffi.Int32,
            ffi.Int32,
            ffi.Uint32,
            ffi.Uint32,
          )
        >
      >('bufferPushScissorRect');
  late final _bufferPushScissorRect = _bufferPushScissorRectPtr
      .asFunction<void Function(int, int, int, int, int)>();

  void bufferPopScissorRect(int buffer) {
    return _bufferPopScissorRect(buffer);
  }

  late final _bufferPopScissorRectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle)>>(
        'bufferPopScissorRect',
      );
  late final _bufferPopScissorRect = _bufferPopScissorRectPtr
      .asFunction<void Function(int)>();

  void bufferClearScissorRects(int buffer) {
    return _bufferClearScissorRects(buffer);
  }

  late final _bufferClearScissorRectsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle)>>(
        'bufferClearScissorRects',
      );
  late final _bufferClearScissorRects = _bufferClearScissorRectsPtr
      .asFunction<void Function(int)>();

  void bufferPushOpacity(int buffer, double opacity) {
    return _bufferPushOpacity(buffer, opacity);
  }

  late final _bufferPushOpacityPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle, ffi.Float)>>(
        'bufferPushOpacity',
      );
  late final _bufferPushOpacity = _bufferPushOpacityPtr
      .asFunction<void Function(int, double)>();

  void bufferPopOpacity(int buffer) {
    return _bufferPopOpacity(buffer);
  }

  late final _bufferPopOpacityPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle)>>(
        'bufferPopOpacity',
      );
  late final _bufferPopOpacity = _bufferPopOpacityPtr
      .asFunction<void Function(int)>();

  void bufferClearOpacity(int buffer) {
    return _bufferClearOpacity(buffer);
  }

  late final _bufferClearOpacityPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle)>>(
        'bufferClearOpacity',
      );
  late final _bufferClearOpacity = _bufferClearOpacityPtr
      .asFunction<void Function(int)>();

  int bufferDrawImage(
    int buffer,
    int image,
    ffi.Pointer<ImageDrawOptions> options,
  ) {
    return _bufferDrawImage(buffer, image, options);
  }

  late final _bufferDrawImagePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint8 Function(
            OpenTuiHandle,
            OpenTuiHandle,
            ffi.Pointer<ImageDrawOptions>,
          )
        >
      >('bufferDrawImage');
  late final _bufferDrawImage = _bufferDrawImagePtr
      .asFunction<int Function(int, int, ffi.Pointer<ImageDrawOptions>)>();

  void setCursorPosition(int renderer, int x, int y, bool visible) {
    return _setCursorPosition(renderer, x, y, visible);
  }

  late final _setCursorPositionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(OpenTuiHandle, ffi.Int32, ffi.Int32, ffi.Bool)
        >
      >('setCursorPosition');
  late final _setCursorPosition = _setCursorPositionPtr
      .asFunction<void Function(int, int, int, bool)>();

  void setCursorStyleOptions(
    int renderer,
    ffi.Pointer<CursorStyleOptions> options,
  ) {
    return _setCursorStyleOptions(renderer, options);
  }

  late final _setCursorStyleOptionsPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(OpenTuiHandle, ffi.Pointer<CursorStyleOptions>)
        >
      >('setCursorStyleOptions');
  late final _setCursorStyleOptions = _setCursorStyleOptionsPtr
      .asFunction<void Function(int, ffi.Pointer<CursorStyleOptions>)>();

  void enableMouse(int renderer, bool enableMovement) {
    return _enableMouse(renderer, enableMovement);
  }

  late final _enableMousePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle, ffi.Bool)>>(
        'enableMouse',
      );
  late final _enableMouse = _enableMousePtr
      .asFunction<void Function(int, bool)>();

  void disableMouse(int renderer) {
    return _disableMouse(renderer);
  }

  late final _disableMousePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle)>>(
        'disableMouse',
      );
  late final _disableMouse = _disableMousePtr.asFunction<void Function(int)>();

  void enableKittyKeyboard(int renderer, int flags) {
    return _enableKittyKeyboard(renderer, flags);
  }

  late final _enableKittyKeyboardPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle, ffi.Uint8)>>(
        'enableKittyKeyboard',
      );
  late final _enableKittyKeyboard = _enableKittyKeyboardPtr
      .asFunction<void Function(int, int)>();

  void disableKittyKeyboard(int renderer) {
    return _disableKittyKeyboard(renderer);
  }

  late final _disableKittyKeyboardPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle)>>(
        'disableKittyKeyboard',
      );
  late final _disableKittyKeyboard = _disableKittyKeyboardPtr
      .asFunction<void Function(int)>();

  void setupTerminal(int renderer, bool useAlternateScreen) {
    return _setupTerminal(renderer, useAlternateScreen);
  }

  late final _setupTerminalPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle, ffi.Bool)>>(
        'setupTerminal',
      );
  late final _setupTerminal = _setupTerminalPtr
      .asFunction<void Function(int, bool)>();

  void queryPixelResolution(int renderer) {
    return _queryPixelResolution(renderer);
  }

  late final _queryPixelResolutionPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle)>>(
        'queryPixelResolution',
      );
  late final _queryPixelResolution = _queryPixelResolutionPtr
      .asFunction<void Function(int)>();

  void addToHitGrid(int renderer, int x, int y, int width, int height, int id) {
    return _addToHitGrid(renderer, x, y, width, height, id);
  }

  late final _addToHitGridPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            OpenTuiHandle,
            ffi.Int32,
            ffi.Int32,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
          )
        >
      >('addToHitGrid');
  late final _addToHitGrid = _addToHitGridPtr
      .asFunction<void Function(int, int, int, int, int, int)>();

  int checkHit(int renderer, int x, int y) {
    return _checkHit(renderer, x, y);
  }

  late final _checkHitPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(OpenTuiHandle, ffi.Uint32, ffi.Uint32)
        >
      >('checkHit');
  late final _checkHit = _checkHitPtr.asFunction<int Function(int, int, int)>();

  void processCapabilityResponse(
    int renderer,
    ffi.Pointer<ffi.Uint8> response,
    int responseLen,
  ) {
    return _processCapabilityResponse(renderer, response, responseLen);
  }

  late final _processCapabilityResponsePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(OpenTuiHandle, ffi.Pointer<ffi.Uint8>, ffi.Uint32)
        >
      >('processCapabilityResponse');
  late final _processCapabilityResponse = _processCapabilityResponsePtr
      .asFunction<void Function(int, ffi.Pointer<ffi.Uint8>, int)>();

  int imageDecode(
    ffi.Pointer<ffi.Uint8> data,
    int dataLen,
    ffi.Pointer<OpenTuiHandle> outHandle,
  ) {
    return _imageDecode(data, dataLen, outHandle);
  }

  late final _imageDecodePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint32,
            ffi.Pointer<OpenTuiHandle>,
          )
        >
      >('imageDecode');
  late final _imageDecode = _imageDecodePtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Uint8>, int, ffi.Pointer<OpenTuiHandle>)
      >();

  int imageCreateFromRgba(
    ffi.Pointer<ffi.Uint8> pixels,
    int pixelsLen,
    int width,
    int height,
    int stride,
    ffi.Pointer<OpenTuiHandle> outHandle,
  ) {
    return _imageCreateFromRgba(
      pixels,
      pixelsLen,
      width,
      height,
      stride,
      outHandle,
    );
  }

  late final _imageCreateFromRgbaPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(
            ffi.Pointer<ffi.Uint8>,
            ffi.Uint64,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Uint32,
            ffi.Pointer<OpenTuiHandle>,
          )
        >
      >('imageCreateFromRgba');
  late final _imageCreateFromRgba = _imageCreateFromRgbaPtr
      .asFunction<
        int Function(
          ffi.Pointer<ffi.Uint8>,
          int,
          int,
          int,
          int,
          ffi.Pointer<OpenTuiHandle>,
        )
      >();

  void imageDestroy(int image) {
    return _imageDestroy(image);
  }

  late final _imageDestroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(OpenTuiHandle)>>(
        'imageDestroy',
      );
  late final _imageDestroy = _imageDestroyPtr.asFunction<void Function(int)>();

  int imageGetInfo(int image, ffi.Pointer<NativeImageInfo> outInfo) {
    return _imageGetInfo(image, outInfo);
  }

  late final _imageGetInfoPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(OpenTuiHandle, ffi.Pointer<NativeImageInfo>)
        >
      >('imageGetInfo');
  late final _imageGetInfo = _imageGetInfoPtr
      .asFunction<int Function(int, ffi.Pointer<NativeImageInfo>)>();

  int linkAlloc(ffi.Pointer<ffi.Uint8> url, int urlLen) {
    return _linkAlloc(url, urlLen);
  }

  late final _linkAllocPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Pointer<ffi.Uint8>, ffi.Uint32)
        >
      >('linkAlloc');
  late final _linkAlloc = _linkAllocPtr
      .asFunction<int Function(ffi.Pointer<ffi.Uint8>, int)>();

  int linkGetUrl(int id, ffi.Pointer<ffi.Uint8> out, int maxLen) {
    return _linkGetUrl(id, out, maxLen);
  }

  late final _linkGetUrlPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Uint32 Function(ffi.Uint32, ffi.Pointer<ffi.Uint8>, ffi.Uint32)
        >
      >('linkGetUrl');
  late final _linkGetUrl = _linkGetUrlPtr
      .asFunction<int Function(int, ffi.Pointer<ffi.Uint8>, int)>();

  int attributesWithLink(int baseAttributes, int linkId) {
    return _attributesWithLink(baseAttributes, linkId);
  }

  late final _attributesWithLinkPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Uint32, ffi.Uint32)>>(
        'attributesWithLink',
      );
  late final _attributesWithLink = _attributesWithLinkPtr
      .asFunction<int Function(int, int)>();

  int attributesGetLinkId(int attributes) {
    return _attributesGetLinkId(attributes);
  }

  late final _attributesGetLinkIdPtr =
      _lookup<ffi.NativeFunction<ffi.Uint32 Function(ffi.Uint32)>>(
        'attributesGetLinkId',
      );
  late final _attributesGetLinkId = _attributesGetLinkIdPtr
      .asFunction<int Function(int)>();
}

/// mbstate_t is an opaque object to keep conversion state, during multibyte
/// stream conversions.  The content must not be referenced by user programs.
final class __mbstate_t extends ffi.Union {
  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> __mbstate8;

  /// for alignment
  @ffi.LongLong()
  external int _mbstateL;
}

final class CursorStyleOptions extends ffi.Struct {
  @ffi.Uint8()
  external int style;

  @ffi.Uint8()
  external int blinking;

  external ffi.Pointer<ffi.Uint16> color;

  @ffi.Uint8()
  external int cursor;
}

final class NativeImageInfo extends ffi.Struct {
  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int sourceWidth;

  @ffi.Uint32()
  external int sourceHeight;

  @ffi.Uint32()
  external int format;

  @ffi.Uint32()
  external int colorStatus;

  @ffi.Uint32()
  external int orientation;

  @ffi.Uint32()
  external int hasAlpha;
}

final class ImageDrawOptions extends ffi.Struct {
  @ffi.Int32()
  external int x;

  @ffi.Int32()
  external int y;

  @ffi.Uint32()
  external int width;

  @ffi.Uint32()
  external int height;

  @ffi.Uint32()
  external int pixelWidth;

  @ffi.Uint32()
  external int pixelHeight;

  @ffi.Uint32()
  external int sourceX;

  @ffi.Uint32()
  external int sourceY;

  @ffi.Uint32()
  external int sourceWidth;

  @ffi.Uint32()
  external int sourceHeight;

  @ffi.Uint32()
  external int protocol;
}

/// Noir-owned declaration of the canonical OpenTUI v0.5.1 exports selected by
/// this package. The source of truth is external/opentui/packages/core/src/zig/
/// lib.zig at ad9a818d7a9d73f3386e92a445d0feb4b395c69e.
typedef OpenTuiHandle = ffi.Uint32;
typedef DartOpenTuiHandle = int;
