// Generated by website/scripts/sync-docs.mjs. Do not edit by hand.
const pages = {
  index: 'Create the screen',
  'store-tasks': 'Store tasks and derive the count',
  'complete-a-task': 'Complete a task',
  'add-a-task': 'Add a task',
  'filter-and-clear': 'Filter and clear completed tasks',
};

export default pages;
